export default (app) => {
  app.post(
    `/tenant/:tenantId/coupons`,
    require('./produitCreate').default,
  );
  app.put(
    `/tenant/:tenantId/coupons/:id`,
    require('./produitUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/coupons/import`,
    require('./produitImport').default,
  );
  app.delete(
    `/tenant/:tenantId/coupons`,
    require('./produitDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/coupons/autocomplete`,
    require('./produitAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/coupons`,
    require('./produitList').default,
  );
  app.get(
    `/tenant/:tenantId/coupons/:id`,
    require('./produitFind').default,
  );
};
